[package]
name = "command"
version = "0.1.0"
edition = "2024"

[package.metadata.component]
package = "component:command"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen-rt = { version = "0.41.0", features = ["bitflags"] }
