package geoloc:dms-conv@0.1.0;

interface dms-conv {
  record DMS {
    degrees: i32,
    minutes: i32,
    seconds: float64,
    direction: string,
  }

  record DMSCoordinates {
    latitude: DMS,
    longitude: DMS,
  }

  import convert: func(normalized: geoloc:coord-norm/coord-norm.NormalizedCoordinates) -> DMSCoordinates;
}

world dms-converter {
    export dms-conv;
    import geoloc:coord-norm/coord-norm;
}
